package com.hkm.emptyactivity.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF006A64)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9CF2EA)
val LightOnPrimaryContainer = Color(0xFF00201E)
val LightSecondary = Color(0xFF4A635F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E3)
val LightOnSecondaryContainer = Color(0xFF06201D)
val LightTertiary = Color(0xFF456179)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCCE5FF)
val LightOnTertiaryContainer = Color(0xFF001E31)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF4FBF8)
val LightOnBackground = Color(0xFF161D1B)
val LightSurface = Color(0xFFF4FBF8)
val LightOnSurface = Color(0xFF161D1B)
val LightSurfaceVariant = Color(0xFFDAE5E2)
val LightOnSurfaceVariant = Color(0xFF3F4947)
val LightOutline = Color(0xFF6F7977)
val LightOutlineVariant = Color(0xFFBEC9C6)

val DarkPrimary = Color(0xFF80D5CE)
val DarkOnPrimary = Color(0xFF003733)
val DarkPrimaryContainer = Color(0xFF00504B)
val DarkOnPrimaryContainer = Color(0xFF9CF2EA)
val DarkSecondary = Color(0xFFB0CCC7)
val DarkOnSecondary = Color(0xFF1C3531)
val DarkSecondaryContainer = Color(0xFF334B47)
val DarkOnSecondaryContainer = Color(0xFFCCE8E3)
val DarkTertiary = Color(0xFFADCAE6)
val DarkOnTertiary = Color(0xFF153349)
val DarkTertiaryContainer = Color(0xFF2D4960)
val DarkOnTertiaryContainer = Color(0xFFCCE5FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1513)
val DarkOnBackground = Color(0xFFDEE4E1)
val DarkSurface = Color(0xFF0E1513)
val DarkOnSurface = Color(0xFFDEE4E1)
val DarkSurfaceVariant = Color(0xFF3F4947)
val DarkOnSurfaceVariant = Color(0xFFBEC9C6)
val DarkOutline = Color(0xFF899390)
val DarkOutlineVariant = Color(0xFF3F4947)
